[2025-03-30T14:10:54.761+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T14:10:54.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_pipelines.train_some scheduled__2025-03-30T14:05:00+00:00 [queued]>
[2025-03-30T14:10:54.790+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_pipelines.train_some scheduled__2025-03-30T14:05:00+00:00 [queued]>
[2025-03-30T14:10:54.791+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T14:10:54.806+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_some> on 2025-03-30 14:05:00+00:00
[2025-03-30T14:10:54.815+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T14:10:54.817+0000] {standard_task_runner.py:72} INFO - Started process 488 to run task
[2025-03-30T14:10:54.818+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_pipelines', 'train_some', 'scheduled__2025-03-30T14:05:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/***_1.py', '--cfg-path', '/tmp/tmpzijkfbds']
[2025-03-30T14:10:54.819+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask train_some
[2025-03-30T14:10:54.859+0000] {task_command.py:467} INFO - Running <TaskInstance: train_pipelines.train_some scheduled__2025-03-30T14:05:00+00:00 [running]> on host cc9d85ccd39f
[2025-03-30T14:10:54.935+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_pipelines' AIRFLOW_CTX_TASK_ID='train_some' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T14:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T14:05:00+00:00'
[2025-03-30T14:10:54.936+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T14:10:54.936+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T14:10:54.937+0000] {logging_mixin.py:190} INFO - Current task name:train_some state:running start_date:2025-03-30 14:10:54.781864+00:00
[2025-03-30T14:10:54.937+0000] {logging_mixin.py:190} INFO - Dag name:train_pipelines and current dag run status:running
[2025-03-30T14:10:54.937+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T14:10:55.116+0000] {logging_mixin.py:190} WARNING - 2025/03/30 14:10:55 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-03-30T14:10:55.129+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-03-30T14:11:36.236+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T14:11:36.247+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T14:11:36.247+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=train_pipelines, task_id=train_some, run_id=scheduled__2025-03-30T14:05:00+00:00, execution_date=20250330T140500, start_date=20250330T141054, end_date=20250330T141136
[2025-03-30T14:11:36.281+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-30T14:11:36.282+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-30T14:11:36.282+0000] {logging_mixin.py:190} INFO - Dag name:train_pipelines queued_at:2025-03-30 14:10:00.298721+00:00
[2025-03-30T14:11:36.283+0000] {logging_mixin.py:190} INFO - Task hostname:cc9d85ccd39f operator:PythonOperator
[2025-03-30T14:11:36.313+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T14:11:36.327+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T14:11:36.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
